// Style Dictionary config for the Eduflick AI design tokens.
//
// Source of truth:  design-system/tokens/tokens.json
// Generated (committed) outputs:
//   - design-system/tokens/tokens.css   → :root custom properties (every surface @imports this)
//   - design-system/tokens/tokens.flat.json → flat name→value map (reference / other tooling)
//   - tools/brand.tokens.mjs             → JS module for the exporter (brand color, mark path, fonts link)
//
// Importing this file registers the custom transform + formats as a side effect.

import StyleDictionary from "style-dictionary";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

// The legacy CSS variable name is the token's leaf key (e.g. color.i-500 → --i-500),
// so the generated names match every existing `var(--…)` reference in the repo.
StyleDictionary.registerTransform({
  name: "name/eduflick-legacy",
  type: "name",
  transform: (token) => token.path[token.path.length - 1],
});

const flatMap = (dictionary) => {
  const obj = {};
  for (const token of dictionary.allTokens) obj[token.name] = token.value;
  return obj;
};

StyleDictionary.registerFormat({
  name: "javascript/eduflick",
  format: ({ dictionary }) =>
    [
      "// AUTO-GENERATED by `npm run tokens` from design-system/tokens/tokens.json.",
      "// Do not edit by hand — edit the JSON and regenerate.",
      `export const tokens = ${JSON.stringify(flatMap(dictionary), null, 2)};`,
      "export const markPath = tokens['mark-path'];",
      "export const fontsLink = tokens['fonts-link'];",
      "export default tokens;",
      "",
    ].join("\n"),
});

StyleDictionary.registerFormat({
  name: "json/eduflick-flat",
  format: ({ dictionary }) => JSON.stringify(flatMap(dictionary), null, 2) + "\n",
});

const notBrand = (token) => token.path[0] !== "brand";

export default {
  source: [resolve(root, "design-system/tokens/tokens.json")],
  platforms: {
    css: {
      transforms: ["name/eduflick-legacy"],
      buildPath: resolve(root, "design-system/tokens") + "/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          filter: notBrand,
          options: { selector: ":root", outputReferences: false },
        },
      ],
    },
    json: {
      transforms: ["name/eduflick-legacy"],
      buildPath: resolve(root, "design-system/tokens") + "/",
      files: [{ destination: "tokens.flat.json", format: "json/eduflick-flat" }],
    },
    js: {
      transforms: ["name/eduflick-legacy"],
      buildPath: resolve(root, "tools") + "/",
      files: [{ destination: "brand.tokens.mjs", format: "javascript/eduflick" }],
    },
  },
};
